global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:4001']
    metrics_path: '/metrics'

  - job_name: 'inventory'
    static_configs:
      - targets: ['inventory:4002']
    metrics_path: '/metrics'

  - job_name: 'shipping'
    static_configs:
      - targets: ['shipping:4003']
    metrics_path: '/metrics'

  - job_name: 'hotel'
    static_configs:
      - targets: ['hotel:4004']
    metrics_path: '/metrics'

  - job_name: 'flight'
    static_configs:
      - targets: ['flight:4005']
    metrics_path: '/metrics'

